name: MailItems
description: Send items to players and recieve items like a mailbox.
main: com.domsplace.MailItemsPlugin
authors: [Dominic]
website: http://domsplace.com/
version: 1.04
load: POSTWORLD
permission: You don't have permission.
commands:
   mailitems:
      description: Reload the MailItems configuration.
      usage: /<command> [player]
      permission: MailItems.reload
   senditem:
      description: Sends an item to another players mailbox
      usage: /<command> [player | all]
      permission: MailItems.senditem
      aliases: [mail, send]
   additem:
      description: Adds an item to another player's mailbox.
      usage: /<command> [player | all] [id(:data)] (amount)
      permission: MailItems.additem
      aliases: [addmail]
   mailbox:
      description: Sets or gets your mailbox.
      usage: /<command> [set]
      permission: MailItems.mailbox
permissions:
   MailItems.*:
     description: Gives access to all MailItems permissions.
     children:
       MailItems.senditem: true
       MailItems.senditem.all: true
       MailItems.reload: true
       MailItems.openmailbox: true
       MailItems.mailbox: true
       MailItems.mailbox.set: true
       MailItems.additem: true
       MailItems.additem.all: true
   MailItems.senditem:
     description: Allows players to send items to each other.
     default: op
   MailItems.additem:
     description: Allows players to add items to someone's mailbox.
     default: op
   MailItems.reload:
     description: Allows a player to reload the configuration.
     default: op
   MailItems.openmailbox:
     description: Allows players to open anyones MailBox.
     default: op
   MailItems.mailbox:
     description: Allows players to check their mailboxes.
     default: op
   MailItems.senditem.all:
     description: Allows a player to send an item to everyone.
     default: op
     children:
       MailItems.senditem: true
   MailItems.additem.all:
     description: Allows a player to add an item to everyone.
     default: op
     children:
       MailItems.additem: true
   MailItems.mailbox.set:
     description: Allows players to set their MailBox.
     default: op
     children:
       MailItems.mailbox: true